# Generated by Django 5.1.1 on 2024-09-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_address', models.CharField(blank=True, max_length=200, null=True)),
                ('client_province', models.CharField(blank=True, choices=[('Cordoba', 'Cordoba'), ('Buenos Aires', 'Buenos Aires'), ('La Pampa', 'La Pampa')], max_length=20)),
                ('client_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
